### PR TITLE
V1.9.0

### PR DESCRIPTION
**Pull request by milkboy**
Preparing to release a new version with all dev-changes

### CODE REVIEW

**Comment by milkboy** [comment]
Anyone have any comments or objections for this? @FZ69617 @wlodek76?

**Comment by FZ69617** [comment]
Just one objection, it would be nice to have also fixes from https://github.com/milkboy/WME-ja/pull/46 included. :)

**Comment by milkboy** [comment]
Included. Also added the missing translations, and ran the code through JSHint -> quite a few changes, of which most are cosmetic, but a few actually required (small) code changes. I think I tested that everything still works as before, but might need some more testing. I'll package (beta) Chome and Firefox extensions at some point, and test those also before releasing the "real" one,

**Comment by FZ69617** [comment]
Added PR #47 which, I hope, finally fixes overlapping checks logic and repairs translations problem mentioned in above comment.

**Pull request merged**
